spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
  datasource:
    url: jdbc:mysql://rm-wz9gp6b7sk45h0nr4qo.mysql.rds.aliyuncs.com:3306/community?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: community
    password: GuptCommunity2019
  redis:
    host: 119.3.181.96
    port: 6379
    password: guptcommunity
  jackson:
    time-zone: GMT+8
    date-format: yyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: net.gupt.community.entity
  configuration:
    map-underscore-to-camel-case: false

pagehelper:
  helper-dialect: mysql

qiniu:
  accessKey: xWM4X5DGsVZVkiyApaDdWVvHikkwJhWAz-wytfP3
  secretKey: hiurTa7ixf3S1lbyvy4AZw2pucnuv2Pn48pfG4b9
  bucket: guptcommunity

server:
  port: 8081
  servlet:
    context-path: /community

logging:
  level:
    net:
      gupt:
        community:
          mapper: debug